/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package javastopwatch;

public class StopwatchMain {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new StopwatchMain().getGreeting());
    }
}
